/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUploadRouteImport } from './routes/_auth/upload'
import { Route as AuthReviewRouteImport } from './routes/_auth/review'
import { Route as AuthReceiptsRouteImport } from './routes/_auth/receipts'
import { Route as AuthGoalsRouteImport } from './routes/_auth/goals'
import { Route as AuthExpensesRouteImport } from './routes/_auth/expenses'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReviewRoute = AuthReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReceiptsRoute = AuthReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGoalsRoute = AuthGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExpensesRoute = AuthExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/expenses': typeof AuthExpensesRoute
  '/goals': typeof AuthGoalsRoute
  '/receipts': typeof AuthReceiptsRoute
  '/review': typeof AuthReviewRoute
  '/upload': typeof AuthUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/expenses': typeof AuthExpensesRoute
  '/goals': typeof AuthGoalsRoute
  '/receipts': typeof AuthReceiptsRoute
  '/review': typeof AuthReviewRoute
  '/upload': typeof AuthUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/expenses': typeof AuthExpensesRoute
  '/_auth/goals': typeof AuthGoalsRoute
  '/_auth/receipts': typeof AuthReceiptsRoute
  '/_auth/review': typeof AuthReviewRoute
  '/_auth/upload': typeof AuthUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/expenses'
    | '/goals'
    | '/receipts'
    | '/review'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/expenses'
    | '/goals'
    | '/receipts'
    | '/review'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/dashboard'
    | '/_auth/expenses'
    | '/_auth/goals'
    | '/_auth/receipts'
    | '/_auth/review'
    | '/_auth/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/review': {
      id: '/_auth/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthReviewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/receipts': {
      id: '/_auth/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthReceiptsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/goals': {
      id: '/_auth/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthGoalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/expenses': {
      id: '/_auth/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthExpensesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthExpensesRoute: typeof AuthExpensesRoute
  AuthGoalsRoute: typeof AuthGoalsRoute
  AuthReceiptsRoute: typeof AuthReceiptsRoute
  AuthReviewRoute: typeof AuthReviewRoute
  AuthUploadRoute: typeof AuthUploadRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthExpensesRoute: AuthExpensesRoute,
  AuthGoalsRoute: AuthGoalsRoute,
  AuthReceiptsRoute: AuthReceiptsRoute,
  AuthReviewRoute: AuthReviewRoute,
  AuthUploadRoute: AuthUploadRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
